"""make_team_ids_nullable_for_knockout_matches

Revision ID: ef31558cca69
Revises: 65ececa79c9a
Create Date: 2026-06-22 11:37:37.824687+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef31558cca69'
down_revision = '65ececa79c9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
